using AlmazayaTravel.Data;
using AlmazayaTravel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Microsoft.Extensions.Logging; // Ensure logger is included

namespace AlmazayaTravel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        // GET: /Home/Index or /
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Fetching active packages for Index page.");
            var activePackages = await _context.TripPackages
                                        .Where(p => p.IsActive)
                                        .OrderBy(p => p.DestinationCountry)
                                        .ToListAsync();
            return View(activePackages);
        }

        // GET: /Home/PackageDetails/5
        public async Task<IActionResult> PackageDetails(int? id)
        {
            _logger.LogInformation("Fetching details for Package ID: {PackageId}", id);
            if (id == null)
            {
                _logger.LogWarning("PackageDetails requested with null ID.");
                return NotFound();
            }

            var tripPackage = await _context.TripPackages
                .FirstOrDefaultAsync(p => p.Id == id && p.IsActive);

            if (tripPackage == null)
            {
                _logger.LogWarning("Package ID {PackageId} not found or inactive.", id);
                return NotFound();
            }

            return View(tripPackage);
        }

        // GET: /Home/Book/5 (ID of the package to book)
        public async Task<IActionResult> Book(int? id)
        {
            _logger.LogInformation("Displaying booking form for Package ID: {PackageId}", id);
            if (id == null)
            {
                _logger.LogWarning("Book action requested with null ID.");
                return NotFound();
            }

            var tripPackage = await _context.TripPackages.FindAsync(id);

            if (tripPackage == null || !tripPackage.IsActive)
            {
                _logger.LogWarning("Package ID {PackageId} not found or inactive for booking.", id);
                TempData["ErrorMessage"] = "The selected package is no longer available.";
                return RedirectToAction(nameof(Index));
            }

            var bookingModel = new Booking
            {
                TripPackageId = tripPackage.Id,
                TripPackage = tripPackage // Pass package details to view
            };

            return View(bookingModel);
        }

        // POST: /Home/Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Book([Bind("TripPackageId,ClientName,PhoneNumber,Email,Adults,Children")] Booking booking)
        {
            _logger.LogInformation("Processing booking form submission for Package ID: {PackageId}", booking.TripPackageId);
            // Remove properties not expected from the form or set later
            ModelState.Remove("TripPackage");
            ModelState.Remove("PaymentStatus");
            ModelState.Remove("PaymentTransactionId");
            ModelState.Remove("AmountPaid");
            ModelState.Remove("BookingDate");
            ModelState.Remove("RowVersion");
            ModelState.Remove("Id"); // Id is generated by DB

            // Fetch the package *before* checking ModelState to ensure it's available for the view if validation fails
            var tripPackage = await _context.TripPackages.AsNoTracking().FirstOrDefaultAsync(tp => tp.Id == booking.TripPackageId);

            if (tripPackage == null || !tripPackage.IsActive)
            {
                _logger.LogWarning("Selected Package ID {PackageId} is not available during booking POST.", booking.TripPackageId);
                ModelState.AddModelError("", "Selected package is not available.");
                // We don't need to fetch TripPackage again here, but return the current booking model.
                // The view needs TripPackage, so it should be assigned before returning.
                // However, the existing 'booking' object doesn't have it loaded. We return View(booking)
                // BUT the view (@model Booking) needs the TripPackage to display info.
                // Re-assigning here before returning view is crucial if modelstate is invalid later.
                // Let's assign it before the IsValid check.
                booking.TripPackage = tripPackage; // Assign here
                return View(booking);
            }
            // Assign the fetched package to the model *now* so it's available if we return the view later
            booking.TripPackage = tripPackage;

            if (ModelState.IsValid)
            {
                booking.BookingDate = DateTime.UtcNow;
                booking.PaymentStatus = "Pending";

                // --- Price Calculation Logic ---
                // TODO: Refine this logic based on actual pricing rules (per person, per package, child discounts etc.)
                decimal pricePerUnit = tripPackage.PriceAfterDiscount ?? tripPackage.PriceBeforeDiscount;
                decimal totalAmount = pricePerUnit * booking.Adults; // Simple example: Price * Adults
                booking.AmountPaid = null; // Reset amount paid
                // --- End Price Calculation ---

                _context.Add(booking);
                await _context.SaveChangesAsync();

                _logger.LogInformation("Booking ID {BookingId} created for Package ID {PackageId}. Redirecting to payment.", booking.Id, booking.TripPackageId);
                return RedirectToAction("Initiate", "Payment", new { bookingId = booking.Id, amount = totalAmount });
            }
            else // ModelState is invalid
            {
                _logger.LogWarning("Booking form submission failed validation for Package ID {PackageId}.", booking.TripPackageId);
                foreach (var state in ModelState)
                {
                    foreach (var error in state.Value.Errors)
                    {
                        _logger.LogDebug("Validation Error ({Key}): {ErrorMessage}", state.Key, error.ErrorMessage);
                    }
                }
                // Return the view with the booking model (TripPackage is already assigned)
                return View(booking);
            }
        }

        // GET: /Home/BookingConfirmation (Optional)
        public async Task<IActionResult> BookingConfirmation()
        {
            if (TempData["BookingId"] == null)
            {
                return RedirectToAction(nameof(Index));
            }
            int bookingId = (int)TempData["BookingId"];
            var booking = await _context.Bookings
                                    .Include(b => b.TripPackage)
                                    .FirstOrDefaultAsync(b => b.Id == bookingId);
            if (booking == null)
            {
                _logger.LogWarning("BookingConfirmation requested for non-existent Booking ID: {BookingId}", bookingId);
                return NotFound();
            }
            TempData.Keep("BookingId");
            return View(booking);
        }

        // GET: /Home/PaymentResult
        public async Task<IActionResult> PaymentResult(bool success = false, string message = "", int? bookingId = null)
        {
            _logger.LogInformation("Displaying PaymentResult page. Success: {Success}, BookingID: {BookingId}, Message: {Message}", success, bookingId, message);
            ViewBag.Success = success;
            ViewBag.Message = message;
            Booking? booking = null;
            if (bookingId.HasValue)
            {
                booking = await _context.Bookings.Include(b => b.TripPackage).FirstOrDefaultAsync(b => b.Id == bookingId.Value);
                if (booking == null) { _logger.LogWarning("Booking ID {BookingId} not found when displaying PaymentResult.", bookingId.Value); }
            }
            return View(booking);
        }

        // --- Static Pages ---
        public IActionResult CancellationPolicy()
        {
            _logger.LogInformation("Displaying Cancellation Policy page.");
            return View();
        }

        // --- Error Handling ---
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var errorViewModel = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };
            _logger.LogError("An error occurred. Request ID: {RequestId}", errorViewModel.RequestId);
            return View(errorViewModel);
        }
    }
}
